# ---------------------------------------------------------------------------
#  SaltyChart Docker-Compose stack
#
#  • Runs the two production images (backend API + frontend static site)
#  • Adds a *named* volume for the SQLite database instead of a bind-mount so
#    the DB survives image upgrades and the file permissions remain correct on
#    Unraid.
#  • Creates an explicit bridge network (salty-net) to ensure the container
#    IPs stay stable between restarts – many Unraid users like to reference
#    them from other stacks or fail2ban rules.
#  • Maps the nginx 80 port to 8085 on the host (that’s what the screenshots
#    in the ticket showed) while keeping the API internal-only.
#  • Accepts an optional TAG env-var so you can switch image revisions without
#    having to edit the file ( `TAG=20250719 docker compose up -d`).  When the
#    var is missing Compose falls back to the latest tag that was previously
#    loaded via `docker load …`.
# ---------------------------------------------------------------------------

services:
  backend:
    image: saltychart-backend:2025-07-27
    container_name: saltychart-backend
    volumes:
      - saltychart_db:/app/prisma
    expose:
      - "3000"
    environment:
      JWT_SECRET: ba2d63b9ffd3fb8f9149456935bf6e70ebac1cb453bef06e8ed5a9b317f410bd
      DATABASE_URL: file:/app/prisma/data.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - salty-net

  frontend:
    image: saltychart-frontend:2025-07-27
    container_name: saltychart-frontend
    volumes:
      - ./frontend:/app:ro     # Optional, can remove if not using for dev
    ports:
      - "8085:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - salty-net

# ---------------------------------------------------------------------------
#  Named resources
# ---------------------------------------------------------------------------

volumes:
  saltychart_db:
    external: true

networks:
  salty-net:
    external: true
